spin_manifest_version = "1"
authors = ["Marius Kluften <mkluften93@gmail.com>"]
description = "Sample project using spin"
name = "add_number"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "add-number"
source = "target/spin-http-js.wasm"
exclude_files = ["**/node_modules"]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
