name: PushRepo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex

    steps:
      - uses: actions/checkout@v2
      - name: Push to another repository
        uses: cpina/github-actions-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: "./"
          destination-github-username: "brehen"
          destination-repository-name: "master-thesis"
          user-email: marius@kluften.dev
          target-branch: main
